### ISSUE TITLE
Menu Swipe Shows Tutorial Pages

### ISSUE THREAD

**Issue by gigocabrera** [driftyco/ionic-conference-app#154]
I installed the latest version of the ionic-conference-app (as of Feb 21, 2016) on my iPhone 6 with iOs 9.2.1 and when I open the menu by taping on the icon and then I swipe the menu back, I see the tutorial pages showing in between (see screenshot below)

![ionic-conference-app-error](https://cloud.githubusercontent.com/assets/6364855/13203175/a457f61e-d87f-11e5-9327-071953da48cc.PNG)

**Comment by vrendina** [comment]
I also noticed the same issue. It occurs when swiping from left to right to open the menu on the schedules page. It only occurs when you have not selected a menu item yet. If I select schedules and then reopen the menu in the same way I do not see the problem. iPhone 5s, iOS 9.2.1 running through Ionic View. 

![img_1274](https://cloud.githubusercontent.com/assets/8770713/13206129/38c8cd82-d8c6-11e5-9a2a-3da99a7f211f.PNG)

**Comment by brandyscarney** [comment]
Thanks for the issue! We are reworking the menu a bit so we should have this fixed in the next release. :smile:

**Comment by jgw96** [comment]
Note: i am still able to reproduce this issue on ios 9.3.1 with the latest version of the conf app

**Comment by brandyscarney** [comment]
I _thought_ this was fixed by my most recent commit, however, I can still reproduce it on the master branch. However, I can't reproduce it on the typescript branch. I believe it is the same as this issue: https://github.com/driftyco/ionic/issues/5575, so I'm going to mark this blocked.

**Comment by gigocabrera** [comment]
@brandyscarney maybe there is still an issue with the menu?
Take a look at this video taken on an iPhone 6 with iOS 9.3.2 (played in slow motion). The Settings page is already opened in the example below. When I tap on the Settings menu item again, it closes the existing Settings page but it also creates a new Settings page that is loaded on top. Not sure if this is a bug but It just feels weird. 

![ionicissue01](https://cloud.githubusercontent.com/assets/6364855/16104727/d1c16306-3351-11e6-9e8d-5e3c4288753f.gif)
